Work around .whl in use during teardown on Windows
I think wheel.install.WheelFile isn't properly managing its handles and
doesn't close the zipfile when it's done with it. Force a gc at tearDown
time to clean up any references and so close the handle prior to the
rmtree done by buildoutTearDown which was failing on Windows with:

WindowsError: [Error 32] The process cannot access the file because it
is being used by another process:
'c:\\...\\_TEST_\\sample_eggs\\demo-1.0-py2-none-any.whl'

Also, can't use self.register_teardown because (bug?) buildoutTearDown
doesn't call the registerd functions in reverse order, so our cleanup
would run *after* the rmtree call regsitered by buildoutSetup, which is
too late.